# Generated by Django 3.1.4 on 2020-12-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_lecturer',
            field=models.BooleanField(),
        ),
    ]
