# Generated by Django 3.1.4 on 2020-12-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lecturer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='practicer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.practicer'),
        ),
    ]
