# Generated by Django 3.1.4 on 2020-12-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lector',
            field=models.ManyToManyField(to='users.Lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ManyToManyField(to='course.Module'),
        ),
        migrations.AddField(
            model_name='course',
            name='practicer',
            field=models.ManyToManyField(to='users.Practicer'),
        ),
        migrations.AddField(
            model_name='contest',
            name='coding',
            field=models.ManyToManyField(to='course.Coding'),
        ),
    ]
