# Generated by Django 3.1.4 on 2020-12-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module'),
        ),
        migrations.AddField(
            model_name='course',
            name='practicer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.practicer'),
        ),
        migrations.AddField(
            model_name='contest',
            name='coding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coding'),
        ),
    ]
