# Generated by Django 3.1.4 on 2020-12-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='users.student'),
        ),
        migrations.AddField(
            model_name='module',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.theory'),
        ),
        migrations.AddField(
            model_name='filling',
            name='examples',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='course.example'),
        ),
        migrations.AddField(
            model_name='contest',
            name='codings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coding'),
        ),
    ]
