# Generated by Django 3.1.4 on 2020-12-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0002_auto_20201214_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
