# Generated by Django 3.1.4 on 2020-12-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
        ('course', '0002_auto_20201220_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lector',
        ),
        migrations.AddField(
            model_name='course',
            name='lector',
            field=models.ManyToManyField(to='users.Lecturer'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ManyToManyField(to='course.Module'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='practicer',
        ),
        migrations.AddField(
            model_name='course',
            name='practicer',
            field=models.ManyToManyField(to='users.Practicer'),
        ),
    ]
