# Generated by Django 3.1.4 on 2020-12-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201220_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachement', models.FileField(upload_to='attachements/')),
            ],
        ),
        migrations.RemoveField(
            model_name='theory',
            name='attachement',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='question',
        ),
        migrations.AddField(
            model_name='theory',
            name='question',
            field=models.ManyToManyField(to='course.Question'),
        ),
        migrations.AddField(
            model_name='theory',
            name='attachement',
            field=models.ManyToManyField(to='course.Attachement'),
        ),
    ]
