# Generated by Django 3.1.4 on 2020-12-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201220_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='coding',
        ),
        migrations.AddField(
            model_name='contest',
            name='coding',
            field=models.ManyToManyField(to='course.Coding'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='attachement',
        ),
        migrations.AddField(
            model_name='project',
            name='attachement',
            field=models.ManyToManyField(to='course.Attachement'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant',
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.ManyToManyField(to='course.Variant'),
        ),
    ]
